# Generated by Codex on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AddField(
            model_name="proposta",
            name="codigo",
            field=models.CharField(default="", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proposta",
            name="nome",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
    ]
