# Generated by Codex on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_proposta_decisao_observacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="clientes/logos/"),
        ),
    ]
