# Generated by Codex on 2026-01-13

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_cliente_logo_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposta",
            name="prioridade",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
            ),
        ),
    ]
