# Generated by Codex on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_proposta_prioridade"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="empresa",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="cliente",
            name="sigla_cidade",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADA", "Aprovada"),
                    ("REPROVADA", "Reprovada"),
                    ("LEVANTAMENTO", "Levantamento"),
                    ("EXECUTANDO", "Executando"),
                    ("FINALIZADO", "Finalizado"),
                ],
                default="PENDENTE",
                max_length=15,
            ),
        ),
    ]
