# Generated by Codex on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_cliente_empresa_status_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposta",
            name="codigo",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
