# Generated by Codex on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_proposta_codigo_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="sigla_cidade",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
