# Generated by Codex on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_cliente_sigla_cidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="tipo",
            field=models.CharField(
                choices=[("CLIENTE", "Cliente"), ("FINANCEIRO", "Financeiro")],
                default="CLIENTE",
                max_length=12,
            ),
        ),
    ]
