# Generated by Codex on 2026-01-13

from django.db import migrations, models


def migrate_tipo_to_m2m(apps, schema_editor):
    Cliente = apps.get_model("core", "Cliente")
    TipoPerfil = apps.get_model("core", "TipoPerfil")
    db_alias = schema_editor.connection.alias

    tipo_cliente, _ = TipoPerfil.objects.using(db_alias).get_or_create(nome="Cliente")
    tipo_financeiro, _ = TipoPerfil.objects.using(db_alias).get_or_create(nome="Financeiro")

    for cliente in Cliente.objects.using(db_alias).all():
        if getattr(cliente, "tipo", None) == "FINANCEIRO":
            cliente.tipos.add(tipo_financeiro)
        else:
            cliente.tipos.add(tipo_cliente)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_cliente_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoPerfil",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipos",
            field=models.ManyToManyField(blank=True, related_name="clientes", to="core.tipoperfil"),
        ),
        migrations.RunPython(migrate_tipo_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="cliente",
            name="tipo",
        ),
    ]
