# Generated by Codex on 2026-01-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_tipo_perfil_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StatusCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=40, unique=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Caderno",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=80)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.TextField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data", models.DateField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("caderno", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="compras", to="core.caderno")),
                ("categoria", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.categoriacompra")),
                ("centro_custo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.centrocusto")),
                ("status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.statuscompra")),
                ("tipo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.tipocompra")),
            ],
        ),
    ]
