# Generated by Codex on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_financeiro_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="caderno",
            name="clientes",
            field=models.ManyToManyField(blank=True, related_name="cadernos", to="core.cliente"),
        ),
    ]
