# Generated by Codex on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_caderno_clientes_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="pago",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="compra",
            name="data_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
