# Generated by Codex on 2026-01-15

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


def seed_io_channel_types(apps, schema_editor):
    TipoCanalIO = apps.get_model("core", "TipoCanalIO")
    defaults = ["DI", "DO", "AI", "AO"]
    for nome in defaults:
        TipoCanalIO.objects.get_or_create(nome=nome, defaults={"ativo": True})


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_compra_pago"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoCanalIO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=20, unique=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="RackIO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                (
                    "slots_total",
                    models.PositiveSmallIntegerField(
                        validators=[MinValueValidator(1), MaxValueValidator(60)]
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="io_racks", to="core.cliente"),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ModuloIO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120)),
                ("modelo", models.CharField(blank=True, max_length=80)),
                ("marca", models.CharField(blank=True, max_length=80)),
                (
                    "quantidade_canais",
                    models.PositiveSmallIntegerField(
                        validators=[MinValueValidator(1), MaxValueValidator(512)]
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="io_modulos",
                        to="core.cliente",
                    ),
                ),
                (
                    "tipo_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modulos_base",
                        to="core.tipocanalio",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="RackSlotIO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("posicao", models.PositiveSmallIntegerField()),
                (
                    "modulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slots",
                        to="core.moduloio",
                    ),
                ),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="core.rackio",
                    ),
                ),
            ],
            options={
                "ordering": ["posicao"],
            },
        ),
        migrations.CreateModel(
            name="CanalIO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("indice", models.PositiveSmallIntegerField()),
                ("nome", models.CharField(blank=True, max_length=120)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canais",
                        to="core.moduloio",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canais",
                        to="core.tipocanalio",
                    ),
                ),
            ],
            options={
                "ordering": ["indice"],
            },
        ),
        migrations.AddConstraint(
            model_name="canalio",
            constraint=models.UniqueConstraint(fields=("modulo", "indice"), name="unique_modulo_canal_indice"),
        ),
        migrations.AddConstraint(
            model_name="rackslotio",
            constraint=models.UniqueConstraint(fields=("rack", "posicao"), name="unique_rack_slot_posicao"),
        ),
        migrations.RunPython(seed_io_channel_types, migrations.RunPython.noop),
    ]
