# Generated by Codex on 2026-01-16

from django.db import migrations, models
import django.db.models.deletion


def migrate_rack_modules(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    RackSlotIO = apps.get_model("core", "RackSlotIO")
    ModuloIO = apps.get_model("core", "ModuloIO")
    ModuloRackIO = apps.get_model("core", "ModuloRackIO")
    CanalIO = apps.get_model("core", "CanalIO")
    CanalRackIO = apps.get_model("core", "CanalRackIO")

    slots = RackSlotIO.objects.using(db_alias).exclude(modulo_id__isnull=True)
    for slot in slots:
        modulo_modelo = ModuloIO.objects.using(db_alias).get(pk=slot.modulo_id)
        modulo_rack = ModuloRackIO.objects.using(db_alias).create(
            rack_id=slot.rack_id,
            modulo_modelo_id=modulo_modelo.id,
            nome=modulo_modelo.nome,
        )
        canais_modelo = CanalIO.objects.using(db_alias).filter(modulo_id=modulo_modelo.id).order_by("indice")
        canais = []
        if canais_modelo.exists():
            for canal in canais_modelo:
                canais.append(
                    CanalRackIO(
                        modulo_id=modulo_rack.id,
                        indice=canal.indice,
                        nome=canal.nome,
                        tipo_id=canal.tipo_id,
                    )
                )
        else:
            for index in range(1, modulo_modelo.quantidade_canais + 1):
                canais.append(
                    CanalRackIO(
                        modulo_id=modulo_rack.id,
                        indice=index,
                        nome=f"Canal {index:02d}",
                        tipo_id=modulo_modelo.tipo_base_id,
                    )
                )
        if canais:
            CanalRackIO.objects.using(db_alias).bulk_create(canais)
        slot.modulo_instancia_id = modulo_rack.id
        slot.save(update_fields=["modulo_instancia"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_io_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuloRackIO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(blank=True, max_length=120)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "modulo_modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instancias",
                        to="core.moduloio",
                    ),
                ),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos",
                        to="core.rackio",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CanalRackIO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("indice", models.PositiveSmallIntegerField()),
                ("nome", models.CharField(blank=True, max_length=120)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canais",
                        to="core.modulorackio",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canais",
                        to="core.tipocanalio",
                    ),
                ),
            ],
            options={
                "ordering": ["indice"],
            },
        ),
        migrations.AddField(
            model_name="rackslotio",
            name="modulo_instancia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slots",
                to="core.modulorackio",
            ),
        ),
        migrations.RunPython(migrate_rack_modules, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="rackslotio",
            name="modulo",
        ),
        migrations.RenameField(
            model_name="rackslotio",
            old_name="modulo_instancia",
            new_name="modulo",
        ),
        migrations.DeleteModel(
            name="CanalIO",
        ),
        migrations.AddConstraint(
            model_name="canalrackio",
            constraint=models.UniqueConstraint(fields=("modulo", "indice"), name="unique_modulo_rack_canal_indice"),
        ),
    ]
