# Generated by Codex on 2026-01-16

from django.db import migrations, models
import django.db.models.deletion


def seed_default_io_modules(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TipoCanalIO = apps.get_model("core", "TipoCanalIO")
    ModuloIO = apps.get_model("core", "ModuloIO")

    tipos = {}
    for nome in ["DI", "DO", "AI", "AO"]:
        tipo, _ = TipoCanalIO.objects.using(db_alias).get_or_create(nome=nome, defaults={"ativo": True})
        tipos[nome] = tipo

    defaults = [
        {"nome": "DI-04", "modelo": "DI-04", "marca": "SET", "canais": 4, "tipo": "DI"},
        {"nome": "DI-08", "modelo": "DI-08", "marca": "SET", "canais": 8, "tipo": "DI"},
        {"nome": "DI-16", "modelo": "DI-16", "marca": "SET", "canais": 16, "tipo": "DI"},
        {"nome": "DI-32", "modelo": "DI-32", "marca": "SET", "canais": 32, "tipo": "DI"},
        {"nome": "DO-04", "modelo": "DO-04", "marca": "SET", "canais": 4, "tipo": "DO"},
        {"nome": "DO-08", "modelo": "DO-08", "marca": "SET", "canais": 8, "tipo": "DO"},
        {"nome": "DO-16", "modelo": "DO-16", "marca": "SET", "canais": 16, "tipo": "DO"},
        {"nome": "DO-32", "modelo": "DO-32", "marca": "SET", "canais": 32, "tipo": "DO"},
        {"nome": "AI-04", "modelo": "AI-04", "marca": "SET", "canais": 4, "tipo": "AI"},
        {"nome": "AI-08", "modelo": "AI-08", "marca": "SET", "canais": 8, "tipo": "AI"},
        {"nome": "AO-04", "modelo": "AO-04", "marca": "SET", "canais": 4, "tipo": "AO"},
        {"nome": "AO-08", "modelo": "AO-08", "marca": "SET", "canais": 8, "tipo": "AO"},
    ]

    for item in defaults:
        ModuloIO.objects.using(db_alias).get_or_create(
            cliente=None,
            nome=item["nome"],
            modelo=item["modelo"],
            marca=item["marca"],
            quantidade_canais=item["canais"],
            tipo_base_id=tipos[item["tipo"]].id,
            is_default=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_io_rack_instances"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduloio",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="io_modulos",
                to="core.cliente",
            ),
        ),
        migrations.AddField(
            model_name="moduloio",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_default_io_modules, migrations.RunPython.noop),
    ]
