# Generated by Codex on 2026-01-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_io_default_modules"),
    ]

    def migrate_caderno_clientes(apps, schema_editor):
        if schema_editor.connection.vendor != "postgresql":
            return
        schema_editor.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'core_caderno'
                      AND column_name = 'cliente_id'
                ) THEN
                    INSERT INTO core_caderno_clientes (caderno_id, cliente_id)
                    SELECT id, cliente_id
                    FROM core_caderno
                    WHERE cliente_id IS NOT NULL
                    ON CONFLICT DO NOTHING;

                    ALTER TABLE core_caderno DROP COLUMN cliente_id;
                END IF;
            END $$;
            """
        )

    operations = [
        migrations.RunPython(migrate_caderno_clientes, reverse_code=migrations.RunPython.noop),
    ]
