# Generated by Codex on 2026-01-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_fix_caderno_cliente_column"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cliente",
            new_name="PerfilUsuario",
        ),
    ]
