# Generated by Codex on 2026-01-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_rename_cliente_perfilusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposta",
            name="criada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propostas_criadas",
                to="auth.user",
            ),
        ),
    ]
