# Generated by Codex on 2026-01-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_proposta_criada_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="caderno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compras",
                to="core.caderno",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.categoriacompra",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="centro_custo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.centrocusto",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="data",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="compra",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="compra",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.statuscompra",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.tipocompra",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="valor",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
