# Generated by Codex on 2026-01-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_compra_campos_opcionais"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantaIO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=40, unique=True)),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="plantas",
            field=models.ManyToManyField(blank=True, related_name="usuarios", to="core.plantaio"),
        ),
        migrations.AddField(
            model_name="rackio",
            name="id_planta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="racks",
                to="core.plantaio",
            ),
        ),
    ]
