# Generated by Codex on 2026-01-16

from django.db import migrations


def add_default_cadernos(apps, schema_editor):
    Caderno = apps.get_model("core", "Caderno")
    PerfilUsuario = apps.get_model("core", "PerfilUsuario")
    capex, _ = Caderno.objects.get_or_create(nome="CAPEX", defaults={"ativo": True})
    opex, _ = Caderno.objects.get_or_create(nome="OPEX", defaults={"ativo": True})
    clientes = PerfilUsuario.objects.all()
    if clientes.exists():
        capex.clientes.add(*clientes)
        opex.clientes.add(*clientes)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_planta_io"),
    ]

    operations = [
        migrations.RunPython(add_default_cadernos, migrations.RunPython.noop),
    ]
