# Generated by Codex on 2026-01-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_default_cadernos"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceiroID",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=40, unique=True)),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="financeiros",
            field=models.ManyToManyField(blank=True, related_name="usuarios", to="core.financeiroid"),
        ),
        migrations.AddField(
            model_name="caderno",
            name="id_financeiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cadernos",
                to="core.financeiroid",
            ),
        ),
    ]
