# Generated by Codex on 2026-01-16

from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


def set_caderno_creator(apps, schema_editor):
    Caderno = apps.get_model("core", "Caderno")
    through = Caderno.clientes.through
    cadernos = Caderno.objects.all()
    for caderno in cadernos:
        if caderno.criador_id:
            continue
        link = through.objects.filter(caderno_id=caderno.id).order_by("id").first()
        if link:
            caderno.criador_id = link.perfilusuario_id
            caderno.save(update_fields=["criador"])
        if not caderno.criado_em:
            caderno.criado_em = timezone.now()
            caderno.save(update_fields=["criado_em"])


def ensure_default_cadernos(apps, schema_editor):
    Caderno = apps.get_model("core", "Caderno")
    PerfilUsuario = apps.get_model("core", "PerfilUsuario")
    for perfil in PerfilUsuario.objects.all():
        if not Caderno.objects.filter(nome="CAPEX", criador_id=perfil.id).exists():
            Caderno.objects.create(nome="CAPEX", ativo=True, criador_id=perfil.id, criado_em=timezone.now())
        if not Caderno.objects.filter(nome="OPEX", criador_id=perfil.id).exists():
            Caderno.objects.create(nome="OPEX", ativo=True, criador_id=perfil.id, criado_em=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_financeiro_id"),
    ]

    atomic = False

    operations = [
        migrations.AddField(
            model_name="caderno",
            name="criador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cadernos_criados",
                to="core.perfilusuario",
            ),
        ),
        migrations.AddField(
            model_name="caderno",
            name="criado_em",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.RunPython(set_caderno_creator, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="caderno",
            name="clientes",
        ),
        migrations.RunPython(ensure_default_cadernos, migrations.RunPython.noop),
    ]
