# Generated by Codex on 2026-01-17

from django.db import migrations, models


def seed_status_proposta(apps, schema_editor):
    StatusProposta = apps.get_model("core", "StatusProposta")
    defaults = [
        ("PENDENTE", "Pendente", 1),
        ("LEVANTAMENTO", "Levantamento", 2),
        ("EXECUTANDO", "Executando", 3),
        ("APROVADA", "Aprovada", 4),
        ("REPROVADA", "Reprovada", 5),
        ("FINALIZADO", "Finalizado", 6),
    ]
    for codigo, nome, ordem in defaults:
        StatusProposta.objects.get_or_create(
            codigo=codigo,
            defaults={"nome": nome, "ativo": True, "ordem": ordem},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_caderno_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusProposta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=60)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.AlterField(
            model_name="proposta",
            name="status",
            field=models.CharField(default="PENDENTE", max_length=20),
        ),
        migrations.RunPython(seed_status_proposta, migrations.RunPython.noop),
    ]
