# Generated by Codex on 2026-01-17

from django.db import migrations, models


def map_proposta_status(apps, schema_editor):
    Proposta = apps.get_model("core", "Proposta")
    for proposta in Proposta.objects.all():
        status = getattr(proposta, "status", None)
        if status == "APROVADA":
            proposta.aprovada = True
        elif status == "REPROVADA":
            proposta.aprovada = False
        else:
            proposta.aprovada = None
        proposta.finalizada = status == "FINALIZADO"
        proposta.save(update_fields=["aprovada", "finalizada"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_status_proposta"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposta",
            name="aprovada",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proposta",
            name="finalizada",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(map_proposta_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="proposta",
            name="status",
        ),
        migrations.DeleteModel(
            name="StatusProposta",
        ),
    ]
