# Generated by Codex on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_proposta_aprovacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="nome",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
