# Generated by Codex on 2026-01-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_compra_nome"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompraItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120)),
                ("valor", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("pago", models.BooleanField(default=False)),
                ("compra", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="core.compra")),
                ("tipo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.tipocompra")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RemoveField(
            model_name="compra",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="status",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="pago",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="data_pagamento",
        ),
    ]
