# Generated by Codex on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_compra_itens"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposta",
            name="andamento",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
