# Generated by Codex on 2026-01-28

from django.db import migrations, models


def _normalize_tag(value):
    if not value:
        return ""
    return "".join(str(value).split()).upper()


def copy_nome_to_tag(apps, schema_editor):
    CanalRackIO = apps.get_model("core", "CanalRackIO")
    for channel in CanalRackIO.objects.all().iterator():
        if channel.tag:
            continue
        base = getattr(channel, "descricao", None)
        if base is None:
            base = getattr(channel, "nome", "")
        channel.tag = _normalize_tag(base)
        channel.save(update_fields=["tag"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_radar_trabalho_campos"),
    ]

    operations = [
        migrations.AddField(
            model_name="canalrackio",
            name="tag",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(copy_nome_to_tag, reverse_code=migrations.RunPython.noop),
    ]
