# Generated by Codex on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_canalrackio_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
