# Generated by Django 6.0.1 on 2026-01-29 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_ingestrecord_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAccessLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("LOGIN", "Login"), ("VIEW", "Visualizacao")], max_length=10)),
                ("path", models.CharField(max_length=512)),
                ("method", models.CharField(max_length=10)),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="adminaccesslog",
            index=models.Index(fields=["user", "created_at"], name="core_admina_user_id_3d8b33_idx"),
        ),
        migrations.AddIndex(
            model_name="adminaccesslog",
            index=models.Index(fields=["action", "created_at"], name="core_admina_action__b7f66c_idx"),
        ),
    ]
