# Generated by Django 6.0.1 on 2026-01-29 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_admin_access_log"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="adminaccesslog",
            name="core_admina_action__b7f66c_idx",
        ),
        migrations.RemoveIndex(
            model_name="adminaccesslog",
            name="core_admina_user_id_3d8b33_idx",
        ),
        migrations.RemoveField(
            model_name="adminaccesslog",
            name="action",
        ),
        migrations.RemoveField(
            model_name="adminaccesslog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="adminaccesslog",
            name="method",
        ),
        migrations.RemoveField(
            model_name="adminaccesslog",
            name="path",
        ),
        migrations.RemoveField(
            model_name="adminaccesslog",
            name="status_code",
        ),
        migrations.RemoveField(
            model_name="adminaccesslog",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="adminaccesslog",
            name="module",
            field=models.CharField(default="home", max_length=120),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="adminaccesslog",
            index=models.Index(fields=["user", "created_at"], name="core_admina_user_id_5c17e0_idx"),
        ),
        migrations.AddIndex(
            model_name="adminaccesslog",
            index=models.Index(fields=["module", "created_at"], name="core_admina_module__8a2f3d_idx"),
        ),
    ]
