# Generated by Django 6.0.1 on 2026-01-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_lista_ip_descricao'),
        ('core', '0055_local_grupo_por_usuario'),
    ]

    operations = [
    ]
