# Generated by Codex on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_merge_20260130_1423"),
        ("core", "0056_rename_canalrackio_nome_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestErrorLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.CharField(blank=True, max_length=120)),
                ("client_id", models.CharField(blank=True, max_length=120)),
                ("agent_id", models.CharField(blank=True, max_length=120)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("error", models.CharField(max_length=120)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                ("raw_body", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ingesterrorlog",
            index=models.Index(fields=["source", "created_at"], name="core_ingest_source__52e4ba_idx"),
        ),
        migrations.AddIndex(
            model_name="ingesterrorlog",
            index=models.Index(fields=["source_id", "created_at"], name="core_ingest_source__7d2f4e_idx"),
        ),
    ]
