# Generated by Codex on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_ingest_error_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(max_length=120, unique=True)),
                ("required_fields", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["source"],
            },
        ),
    ]
