# Generated by Codex on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_ingest_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingesterrorlog",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ingesterrorlog",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
