# Generated by Django 6.0.1 on 2026-02-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_proposta_valor_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ingest_agent_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='app',
            name='ingest_client_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='app',
            name='ingest_source',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='AppRotasMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ORIGEM', 'ORIGEM'), ('DESTINO', 'DESTINO')], max_length=20)),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_maps', to='core.app')),
            ],
            options={
                'ordering': ['app_id', 'tipo', 'codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='ingestrecord',
            index=models.Index(fields=['client_id', 'agent_id', 'source', 'created_at'], name='core_ingest_client__15ede2_idx'),
        ),
        migrations.AddConstraint(
            model_name='approtasmap',
            constraint=models.UniqueConstraint(fields=('app', 'tipo', 'codigo'), name='unique_app_rotas_map'),
        ),
    ]
