# Generated by Django 6.0.1 on 2026-03-11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_recalculate_atividade_horas_colaboradores"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadarTrabalhoObservacao",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texto", models.TextField()),
                ("data_observacao", models.DateField(default=django.utils.timezone.localdate)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "trabalho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="core.radartrabalho",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_observacao", "-id"],
            },
        ),
    ]
