# Generated by Django 5.2.11 on 2026-04-12 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_io_import_pipeline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingestrecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="moduloio",
            options={"ordering": ["modelo", "id"]},
        ),
        migrations.RenameIndex(
            model_name="adminaccesslog",
            new_name="core_admina_user_id_67a7ed_idx",
            old_name="core_admina_user_id_5c17e0_idx",
        ),
        migrations.RenameIndex(
            model_name="adminaccesslog",
            new_name="core_admina_module_e24d3c_idx",
            old_name="core_admina_module__8a2f3d_idx",
        ),
        migrations.RenameIndex(
            model_name="appmilhaoblamuraldialeitura",
            new_name="core_appmil_usuario_7d06c9_idx",
            old_name="core_appmil_usuario_3f9f2d_idx",
        ),
        migrations.RenameIndex(
            model_name="ingesterrorlog",
            new_name="core_ingest_source_1c8173_idx",
            old_name="core_ingest_source__52e4ba_idx",
        ),
        migrations.RenameIndex(
            model_name="ingesterrorlog",
            new_name="core_ingest_source__29c6f7_idx",
            old_name="core_ingest_source__7d2f4e_idx",
        ),
        migrations.RenameIndex(
            model_name="ioimportjob",
            new_name="core_ioimpo_status_2c7d3e_idx",
            old_name="core_ioimpo_status_81e4d0_idx",
        ),
        migrations.RenameIndex(
            model_name="ioimportjob",
            new_name="core_ioimpo_ai_stat_a06dbc_idx",
            old_name="core_ioimpo_ai_stat_40d0a0_idx",
        ),
        migrations.AlterField(
            model_name="acessoprodutousuario",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="adminaccesslog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="approtaconfig",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="approtasmap",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="caderno",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="caderno",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="canalrackio",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="categoriacompra",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="centrocusto",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="compraitem",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="compraitem",
            name="parcela",
            field=models.CharField(
                default="1/1",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Parcela deve estar no formato 01/36 ou 1/-.",
                        regex="^\\d{1,5}/\\d{1,5}$|^1/-$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="compraitem",
            name="quantidade",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="financeiroid",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ingesterrorlog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ingestrecord",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ingestrule",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="tagset_pattern",
            field=models.CharField(
                choices=[
                    ("TIPO_SEQ", "Sequencial por tipo"),
                    ("SETORIZADO", "Setorizado"),
                    ("INVENTARIO", "Inventario + tipo"),
                ],
                default="TIPO_SEQ",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ioimportjob",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ioimportsettings",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="listaip",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="listaipid",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="listaipitem",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="moduloacesso",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="moduloio",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="modulorackio",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="plantaio",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="produtoplataforma",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rackio",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rackslotio",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="statuscompra",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tipocanalio",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tipocompra",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tipoperfil",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
