# Generated by Django 5.2.11 on 2026-04-12 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_alter_ingestrecord_options_alter_moduloio_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IPImportSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("OPENAI", "OpenAI")], default="OPENAI", max_length=20
                    ),
                ),
                ("api_key", models.CharField(blank=True, default="", max_length=255)),
                (
                    "api_base_url",
                    models.CharField(
                        blank=True, default="https://api.openai.com/v1", max_length=255
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, default="gpt-5-mini", max_length=120),
                ),
                (
                    "reasoning_effort",
                    models.CharField(blank=True, default="medium", max_length=20),
                ),
                ("max_rows_for_ai", models.PositiveIntegerField(default=180)),
                ("header_prompt", models.TextField(blank=True, default="")),
                ("grouping_prompt", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ip_import_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuracao de importacao IP",
                "verbose_name_plural": "Configuracoes de importacao IP",
            },
        ),
        migrations.CreateModel(
            name="IPImportJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Upload recebido"),
                            ("REVIEW", "Pronto para revisao"),
                            ("APPLIED", "Aplicado"),
                            ("FAILED", "Falhou"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                            ("tsv", "TSV"),
                            ("unknown", "Desconhecido"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("source_file", models.FileField(upload_to="ip/imports/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "sheet_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "header_row_index",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("rows_total", models.PositiveIntegerField(default=0)),
                ("rows_parsed", models.PositiveIntegerField(default=0)),
                (
                    "ai_status",
                    models.CharField(
                        choices=[
                            ("SKIPPED", "Nao executado"),
                            ("SUCCESS", "Concluido"),
                            ("FAILED", "Falhou"),
                        ],
                        default="SKIPPED",
                        max_length=20,
                    ),
                ),
                ("ai_model", models.CharField(blank=True, default="", max_length=120)),
                ("ai_error", models.TextField(blank=True, default="")),
                ("column_map", models.JSONField(blank=True, default=dict)),
                ("extracted_payload", models.JSONField(blank=True, default=dict)),
                ("proposal_payload", models.JSONField(blank=True, default=dict)),
                ("ai_payload", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("apply_log", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_lista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs_applied",
                        to="core.listaip",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_import_jobs",
                        to="core.perfilusuario",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ip_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_ipimpo_status_3777f2_idx",
                    ),
                    models.Index(
                        fields=["ai_status", "created_at"],
                        name="core_ipimpo_ai_stat_ddcd01_idx",
                    ),
                ],
            },
        ),
    ]
