# Generated by Django 5.2.11 on 2026-04-13 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_billing_foundation(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ProdutoPlataforma = apps.get_model("core", "ProdutoPlataforma")
    PlanoComercial = apps.get_model("core", "PlanoComercial")
    ConfiguracaoPagamento = apps.get_model("core", "ConfiguracaoPagamento")

    product, _ = ProdutoPlataforma.objects.using(db_alias).get_or_create(
        codigo="DOCUMENTACAO_TECNICA",
        defaults={
            "nome": "Documentacao tecnica",
            "descricao": "Acesso conjunto aos modulos de IOs e Listas de IP.",
            "ativo": True,
        },
    )
    PlanoComercial.objects.using(db_alias).get_or_create(
        produto_id=product.id,
        codigo="STARTER",
        defaults={
            "nome": "Plano Iniciante",
            "descricao": "Uso gratuito apos o trial com ate 3 racks simultaneos.",
            "ativo": True,
            "is_free": True,
            "ordem": 10,
            "rack_limit_simultaneous": 3,
            "preco_mensal": 0,
            "preco_anual": 0,
        },
    )
    PlanoComercial.objects.using(db_alias).get_or_create(
        produto_id=product.id,
        codigo="PROFESSIONAL",
        defaults={
            "nome": "Plano Profissional",
            "descricao": "Uso completo com racks ilimitados.",
            "ativo": True,
            "is_free": False,
            "ordem": 20,
            "rack_limit_simultaneous": None,
        },
    )
    ConfiguracaoPagamento.objects.using(db_alias).get_or_create(
        pk=1,
        defaults={
            "trial_duration_days": 30,
            "enabled": False,
            "provider": "MERCADO_PAGO",
            "sandbox_mode": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_ipimportsettings_ipimportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoPagamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trial_duration_days", models.PositiveIntegerField(default=30)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("MERCADO_PAGO", "Mercado Pago")],
                        default="MERCADO_PAGO",
                        max_length=20,
                    ),
                ),
                ("sandbox_mode", models.BooleanField(default=True)),
                (
                    "mercado_pago_public_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "mercado_pago_access_token",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "mercado_pago_webhook_secret",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "checkout_success_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "checkout_failure_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "checkout_pending_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_configuration_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuracao de pagamento",
                "verbose_name_plural": "Configuracoes de pagamento",
            },
        ),
        migrations.CreateModel(
            name="EventoPagamentoWebhook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("MERCADO_PAGO", "Mercado Pago")], max_length=20
                    ),
                ),
                ("external_id", models.CharField(max_length=120)),
                (
                    "event_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-received_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_id"),
                        name="unique_pagamento_webhook_event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanoComercial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("PROFESSIONAL", "Professional"),
                        ],
                        max_length=40,
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("is_free", models.BooleanField(default=False)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "rack_limit_simultaneous",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "preco_mensal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "preco_anual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "provider_plan_code_mensal",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "provider_plan_code_anual",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planos",
                        to="core.produtoplataforma",
                    ),
                ),
            ],
            options={
                "ordering": ["produto__nome", "ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="AssinaturaUsuario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Interno"),
                            ("MERCADO_PAGO", "Mercado Pago"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("ACTIVE", "Ativa"),
                            ("PAST_DUE", "Em atraso"),
                            ("CANCELED", "Cancelada"),
                            ("EXPIRED", "Expirada"),
                            ("TRIALING", "Em trial"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[("MONTHLY", "Mensal"), ("YEARLY", "Anual")],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "preco_ciclo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("moeda", models.CharField(blank=True, default="BRL", max_length=12)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_customer_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "provider_subscription_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "provider_plan_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "external_reference",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("checkout_url", models.TextField(blank=True, default="")),
                ("observacao", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="core.produtoplataforma",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assinaturas",
                        to="core.planocomercial",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="planocomercial",
            constraint=models.UniqueConstraint(
                fields=("produto", "codigo"),
                name="unique_plano_comercial_produto_codigo",
            ),
        ),
        migrations.AddIndex(
            model_name="assinaturausuario",
            index=models.Index(
                fields=["status", "updated_at"], name="core_assina_status_7b0f95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assinaturausuario",
            index=models.Index(
                fields=["provider", "provider_subscription_id"],
                name="core_assina_provide_01aaa9_idx",
            ),
        ),
        migrations.RunPython(seed_billing_foundation, migrations.RunPython.noop),
    ]
