# Generated by Django 5.2.11 on 2026-04-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_configuracaopagamento_eventopagamentowebhook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ioimportjob",
            name="progress_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
