# Generated by Django 5.2.11 on 2026-04-14 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_ipimportaicache_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumoImportacaoDiaria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[("IO", "IO"), ("IP", "IP")], max_length=8
                    ),
                ),
                ("referencia_data", models.DateField()),
                ("importacoes_bem_sucedidas", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "-referencia_data",
                    "produto__nome",
                    "modulo",
                    "usuario__username",
                ],
            },
        ),
        migrations.AddField(
            model_name="configuracaopagamento",
            name="trial_daily_io_import_limit",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="configuracaopagamento",
            name="trial_daily_ip_import_limit",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="ioimportjob",
            name="first_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ipimportjob",
            name="first_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planocomercial",
            name="daily_io_import_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planocomercial",
            name="daily_ip_import_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="ioimportjob",
            index=models.Index(
                fields=["created_by", "first_applied_at"],
                name="core_ioimpo_created_e114bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ipimportjob",
            index=models.Index(
                fields=["created_by", "first_applied_at"],
                name="core_ipimpo_created_92afdb_idx",
            ),
        ),
        migrations.AddField(
            model_name="consumoimportacaodiaria",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumos_importacao_diaria",
                to="core.produtoplataforma",
            ),
        ),
        migrations.AddField(
            model_name="consumoimportacaodiaria",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumos_importacao_diaria",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="consumoimportacaodiaria",
            index=models.Index(
                fields=["produto", "modulo", "referencia_data"],
                name="core_consum_produto_02e014_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="consumoimportacaodiaria",
            constraint=models.UniqueConstraint(
                fields=("usuario", "produto", "modulo", "referencia_data"),
                name="unique_consumo_importacao_diaria_usuario_produto_modulo_data",
            ),
        ),
    ]
