# Generated by Django 5.2.11 on 2026-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_stripe_provider_refactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="anexo_foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="financeiro/compras/"
            ),
        ),
    ]
